name: Build

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build-release-binaries:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, freebsd, linux, netbsd, openbsd, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: wangyoucao577/go-release-action@v1
        env:
          CGO_ENABLED: 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: -s -w
          build_flags: -trimpath
          overwrite: true
          sha256sum: true
          md5sum: false
          asset_name: whatismyip-${{ matrix.goos }}-${{ matrix.goarch }}
          compress_assets: false
